[2025-03-05T11:08:04.670+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T11:08:04.685+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v01.task1 manual__2025-03-05T11:08:04.125218+00:00 [queued]>
[2025-03-05T11:08:04.694+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v01.task1 manual__2025-03-05T11:08:04.125218+00:00 [queued]>
[2025-03-05T11:08:04.694+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-05T11:08:04.708+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task1> on 2025-03-05 11:08:04.125218+00:00
[2025-03-05T11:08:04.717+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v01', 'task1', 'manual__2025-03-05T11:08:04.125218+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_backfill.py', '--cfg-path', '/tmp/tmpc2uy9jqn']
[2025-03-05T11:08:04.719+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask task1
[2025-03-05T11:08:04.720+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=338) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-05T11:08:04.721+0000] {standard_task_runner.py:72} INFO - Started process 339 to run task
[2025-03-05T11:08:04.771+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_backfill_v01.task1 manual__2025-03-05T11:08:04.125218+00:00 [running]> on host 9f9d6a721d56
[2025-03-05T11:08:04.846+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naveen' AIRFLOW_CTX_DAG_ID='dag_with_catchup_backfill_v01' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T11:08:04.125218+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-05T11:08:04.125218+00:00'
[2025-03-05T11:08:04.846+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-05T11:08:04.861+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-05T11:08:04.861+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo This is a simple bash command!']
[2025-03-05T11:08:04.873+0000] {subprocess.py:99} INFO - Output:
[2025-03-05T11:08:04.875+0000] {subprocess.py:106} INFO - This is a simple bash command!
[2025-03-05T11:08:04.875+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-05T11:08:04.906+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-05T11:08:04.907+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_backfill_v01, task_id=task1, run_id=manual__2025-03-05T11:08:04.125218+00:00, execution_date=20250305T110804, start_date=20250305T110804, end_date=20250305T110804
[2025-03-05T11:08:04.975+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-05T11:08:04.996+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-05T11:08:04.998+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
