[2025-03-04T07:00:47.396+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-04T07:00:47.417+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v01.task1 manual__2025-03-04T07:00:46.808220+00:00 [queued]>
[2025-03-04T07:00:47.422+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_backfill_v01.task1 manual__2025-03-04T07:00:46.808220+00:00 [queued]>
[2025-03-04T07:00:47.423+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-04T07:00:47.438+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): task1> on 2025-03-04 07:00:46.808220+00:00
[2025-03-04T07:00:47.445+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=257) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-04T07:00:47.444+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup_backfill_v01', 'task1', 'manual__2025-03-04T07:00:46.808220+00:00', '--job-id', '248', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catchup_backfill.py', '--cfg-path', '/tmp/tmpbratvwa6']
[2025-03-04T07:00:47.446+0000] {standard_task_runner.py:72} INFO - Started process 258 to run task
[2025-03-04T07:00:47.446+0000] {standard_task_runner.py:105} INFO - Job 248: Subtask task1
[2025-03-04T07:00:47.500+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_catchup_backfill_v01.task1 manual__2025-03-04T07:00:46.808220+00:00 [running]> on host a05f2e7fadc5
[2025-03-04T07:00:47.606+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='naveen' AIRFLOW_CTX_DAG_ID='dag_with_catchup_backfill_v01' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-03-04T07:00:46.808220+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-04T07:00:46.808220+00:00'
[2025-03-04T07:00:47.608+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-04T07:00:47.624+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-04T07:00:47.624+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo This is a simple bash command!']
[2025-03-04T07:00:47.634+0000] {subprocess.py:99} INFO - Output:
[2025-03-04T07:00:47.636+0000] {subprocess.py:106} INFO - This is a simple bash command!
[2025-03-04T07:00:47.636+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-03-04T07:00:47.673+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-04T07:00:47.673+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_backfill_v01, task_id=task1, run_id=manual__2025-03-04T07:00:46.808220+00:00, execution_date=20250304T070046, start_date=20250304T070047, end_date=20250304T070047
[2025-03-04T07:00:47.741+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-04T07:00:47.771+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-04T07:00:47.777+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
